version: "3"
services:
  Jenkins:
    image: jenkins/jenkins:jdk21
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - selenium-grid
    restart: on-failure

  HubService:
    image: selenium/hub:4.9.0
    container_name: seleniumHub
    ports:
      - "4445:4444"
      - "4442:4442"
      - "4443:4443"
    networks:
      - selenium-grid

  ChromeService:
    image: selenium/node-chrome:4.9.0
    shm_size: "2gb"
    ports:
      - "5900:5900"
    environment:
      - SE_EVENT_BUS_HOST=seleniumHub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_VNC_NO_PASSWORD=1
    depends_on:
      - HubService
    networks:
      - selenium-grid

  FirefoxService:
    image: selenium/node-firefox:4.9.0
    shm_size: "2gb"
    ports:
      - "5901:5900"
    environment:
      - SE_EVENT_BUS_HOST=seleniumHub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_VNC_NO_PASSWORD=1
    depends_on:
      - HubService
    networks:
      - selenium-grid

  EdgeService:
    image: selenium/node-edge:4.9.0
    shm_size: "2gb"
    ports:
      - "5902:5900"
    environment:
      - SE_EVENT_BUS_HOST=seleniumHub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_VNC_NO_PASSWORD=1
    depends_on:
      - HubService
    networks:
      - selenium-grid

networks:
  selenium-grid:
    driver: bridge

volumes:
  jenkins_home: